
//! Autogenerated weights for `pallet_commitments`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2026-01-29, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `trevor-benchmark`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/sxt-node
// benchmark
// pallet
// --pallet
// pallet_commitments
// --extrinsic
// *
// --steps=50
// --external-repeat=20
// --wasm-execution=compiled
// --template
// ./pallets/frame-weight-template.hbs
// --output
// ./pallets/commitments/src/migrations/delete_dynamic_dory/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use polkadot_sdk::frame_system;
use core::marker::PhantomData;

/// Weight functions needed for `pallet_commitments`.
pub trait WeightInfo {
	fn step() -> Weight;
}

/// Weights for `pallet_commitments` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:1)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	fn step() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `96934`
		// Minimum execution time: 11_251_000 picoseconds.
		Weight::from_parts(11_963_000, 96934)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:1)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	fn step() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `96934`
		// Minimum execution time: 11_251_000 picoseconds.
		Weight::from_parts(11_963_000, 96934)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
