
//! Autogenerated weights for `pallet_attestation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-10-31, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `trevor-benchmark`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/sxt-node
// benchmark
// pallet
// --pallet
// pallet_attestation
// --extrinsic
// *
// --steps=50
// --external-repeat=20
// --wasm-execution=compiled
// --template
// ./pallets/frame-weight-template.hbs
// --output
// ./pallets/attestation/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_attestation`.
pub trait WeightInfo {
	fn attest_block() -> Weight;
	fn mark_block_forwarded() -> Weight;
}

/// Weights for `pallet_attestation` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Keystore::Keys` (r:1 w:0)
	/// Proof: `Keystore::Keys` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
	/// Storage: `Attestations::Attestations` (r:1 w:1)
	/// Proof: `Attestations::Attestations` (`max_values`: None, `max_size`: Some(14230), added: 16705, mode: `MaxEncodedLen`)
	fn attest_block() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `17695`
		// Minimum execution time: 752_075_000 picoseconds.
		Weight::from_parts(756_523_000, 17695)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestations::LastForwardedBlock` (r:0 w:1)
	/// Proof: `Attestations::LastForwardedBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn mark_block_forwarded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `81`
		//  Estimated: `3546`
		// Minimum execution time: 13_274_000 picoseconds.
		Weight::from_parts(13_796_000, 3546)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Keystore::Keys` (r:1 w:0)
	/// Proof: `Keystore::Keys` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
	/// Storage: `Attestations::Attestations` (r:1 w:1)
	/// Proof: `Attestations::Attestations` (`max_values`: None, `max_size`: Some(14230), added: 16705, mode: `MaxEncodedLen`)
	fn attest_block() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `17695`
		// Minimum execution time: 752_075_000 picoseconds.
		Weight::from_parts(756_523_000, 17695)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestations::LastForwardedBlock` (r:0 w:1)
	/// Proof: `Attestations::LastForwardedBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn mark_block_forwarded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `81`
		//  Estimated: `3546`
		// Minimum execution time: 13_274_000 picoseconds.
		Weight::from_parts(13_796_000, 3546)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
