CREATE TABLE IF NOT EXISTS ETHEREUM.CONTRACT_EVT_APPROVALFORALL(
  BLOCK_NUMBER BIGINT NOT NULL,
  TIME_STAMP TIMESTAMP NOT NULL,
  TRANSACTION_HASH VARCHAR NOT NULL,
  EVENT_INDEX INT NOT NULL,
  OPERATOR VARCHAR NOT NULL,
  ACCOUNT VARCHAR NOT NULL,
  APPROVED BOOLEAN NOT NULL,
  CONTRACT_ADDRESS VARCHAR NOT NULL,
  PRIMARY KEY(BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
);

CREATE TABLE IF NOT EXISTS ETHEREUM.CONTRACT_EVT_OWNERSHIPTRANSFERRED(
  BLOCK_NUMBER BIGINT NOT NULL,
  TIME_STAMP TIMESTAMP NOT NULL,
  TRANSACTION_HASH VARCHAR NOT NULL,
  EVENT_INDEX INT NOT NULL,
  PREVIOUSOWNER VARCHAR NOT NULL,
  NEWOWNER VARCHAR NOT NULL,
  CONTRACT_ADDRESS VARCHAR NOT NULL,
  PRIMARY KEY(BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
);

CREATE TABLE IF NOT EXISTS ETHEREUM.ERC1155_EVT_TRANSFERBATCH(
  TRANSACTION_HASH VARCHAR NOT NULL,
  EVENT_INDEX INT NOT NULL,
  OPERATOR VARCHAR NOT NULL,
  BLOCK_NUMBER BIGINT NOT NULL,
  TIME_STAMP TIMESTAMP NOT NULL,
  FROM_ VARCHAR NOT NULL,
  TO_ VARCHAR NOT NULL,
  CONTRACT_ADDRESS VARCHAR NOT NULL,
  VALUES_ VARCHAR NOT NULL,
  IDS VARCHAR NOT NULL,
  PRIMARY KEY(BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
);