[package]
name = "pallet-attestation"
description = "SxT Pallet for providing on chain attestation"
version = "0.1.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = [
	"derive",
], workspace = true }
scale-info = { features = [
	"derive",
], workspace = true }

polkadot-sdk = { workspace = true, features = [
	"frame-benchmarking", "frame-support", "frame-system"
]}
k256 = { version = "0.13.4", default-features = false }
sha3 = { version = "0.10.8", default-features = false }
sxt-core.workspace = true
pallet-permissions.workspace = true
pallet-keystore.workspace = true

[dev-dependencies]
polkadot-sdk = { workspace = true, features = [
	"sp-io", "sp-runtime", "sp-core",
]}

[features]
default = ["std"]
std = [
	"pallet-permissions/std",
	"pallet-keystore/std",
	"codec/std",
	"scale-info/std",
	"k256/std",
	"sha3/std",
	"sxt-core/std",
	"polkadot-sdk/std",
]
runtime-benchmarks = [
	"polkadot-sdk/runtime-benchmarks",
]
try-runtime = [
	"polkadot-sdk/try-runtime",
]
