[package]
name = "node-rpc"
version = "0.1.0"
authors.workspace = true
description = "Space and Time node rpc methods."
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
polkadot-sdk = { workspace = true, features = [
    "frame-support",
    "sc-chain-spec",
    "sc-client-api",
    "sc-consensus-babe",
    "sc-consensus-babe-rpc",
    "sc-consensus-grandpa",
    "sc-consensus-grandpa-rpc",
    "sc-rpc",
    "sc-sync-state-rpc",
    "sc-transaction-pool-api",
    "pallet-transaction-payment-rpc",
    "pallet-balances",
    "sp-api",
    "sp-block-builder",
    "sp-blockchain",
    "sp-consensus",
    "sp-consensus-babe",
    "sp-core",
    "sp-keystore",
    "sp-runtime",
    "sp-statement-store",
    "substrate-frame-rpc-system",
    "substrate-state-trie-migration-rpc",
]}

attestation_tree.workspace = true
bincode.workspace = true
codec.workspace = true
datafusion.workspace = true
indexmap = { workspace = true }
jsonrpsee = { features = ["server"], workspace = true }
pallet-attestation = { workspace = true, default-features = false, features = ["std"] }
pallet-system-contracts = { workspace = true, default-features = true }
proof-of-sql = { workspace = true }
proof-of-sql-planner = { workspace = true }
proof-of-sql-commitment-map = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
sqlparser = { workspace = true, features = ["std", "visitor"] }
sxt-core = { workspace = true }
sxt-runtime = { workspace = true, default-features = false, features = ["std"] }

[dev-dependencies]
proof-of-sql-static-setups = { workspace = true, features = ["io"] }
commitment-sql = { workspace = true }
on-chain-table.workspace = true
itertools.workspace = true
hex.workspace = true
