CREATE TABLE IF NOT EXISTS ETHEREUM.CONTRACT_EVT_APPROVALFORALL(
  BLOCK_NUMBER BIGINT,
  TIME_STAMP TIMESTAMP,
  TRANSACTION_HASH VARCHAR,
  EVENT_INDEX INT,
  OPERATOR VARCHAR,
  ACCOUNT VARCHAR,
  APPROVED BOOLEAN,
  CONTRACT_ADDRESS VARCHAR,
  PRIMARY KEY(BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
);

CREATE TABLE IF NOT EXISTS ETHEREUM.CONTRACT_EVT_OWNERSHIPTRANSFERRED(
  BLOCK_NUMBER BIGINT,
  TIME_STAMP TIMESTAMP,
  TRANSACTION_HASH VARCHAR,
  EVENT_INDEX INT,
  PREVIOUSOWNER VARCHAR,
  NEWOWNER VARCHAR,
  CONTRACT_ADDRESS VARCHAR,
  PRIMARY KEY(BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
);

CREATE TABLE IF NOT EXISTS ETHEREUM.ERC1155_EVT_TRANSFERBATCH(
  TRANSACTION_HASH VARCHAR,
  EVENT_INDEX INT,
  OPERATOR VARCHAR,
  BLOCK_NUMBER BIGINT,
  TIME_STAMP TIMESTAMP,
  FROM_ VARCHAR,
  TO_ VARCHAR,
  CONTRACT_ADDRESS VARCHAR,
  VALUES_ VARCHAR,
  IDS VARCHAR,
  PRIMARY KEY(BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
);