[package]
name = "commitment-column-mapping"
version = "0.1.0"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
proof-of-sql.workspace = true
proof-of-sql-commitment-map = { workspace = true, features = ["substrate"] }
on-chain-table.workspace = true
sqlparser.workspace = true
snafu.workspace = true

[dev-dependencies]
commitment-sql.workspace = true
proof-of-sql-static-setups = { workspace = true, features = ["io"] }
# simply enables many std features of polkadot crates, avoiding std conflicts
sxt-core = { workspace = true, features = ["std"] }

[lints]
workspace = true
