[package]
name = "sxt-runtime"
description = "Space and Time Transaction Node Runtime"
version = "0.1.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = [
	"derive",
], workspace = true }
scale-info = { features = [
	"derive",
	"serde",
], workspace = true }
eth-ecdsa = { workspace = true }

polkadot-sdk = { workspace = true, features = [
	"frame-executive",
	"pallet-aura",
	"pallet-balances",
	"pallet-grandpa",
	"pallet-sudo",
	"pallet-multisig",
	"pallet-migrations",
	"pallet-timestamp",
	"sp-api",
	"sp-block-builder",
	"sp-consensus-aura",
	"sp-consensus-grandpa",
	"sp-core",
	"sp-inherents",
	"sp-offchain",
	"sp-runtime",
	"sp-session",
	"sp-storage",
	"sp-version",
	"frame-benchmarking",
	"frame-system-benchmarking",
	"pallet-staking",
	"pallet-staking-runtime-api",
	"pallet-authorship",
	"pallet-im-online",
	"pallet-offences",
	"pallet-authority-discovery",
	"pallet-election-provider-multi-phase",
	"pallet-babe",
	"pallet-indices",
	"frame-support",
	"frame-system",
	"frame-try-runtime",
	"pallet-transaction-payment",
	"sp-transaction-pool",
	"sp-genesis-builder",
	"frame-system-rpc-runtime-api",
	"pallet-transaction-payment-rpc-runtime-api",
	"sp-consensus-babe",
	"sp-staking",
	"frame-election-provider-support",
	"pallet-bags-list",
	"pallet-utility",
	"sp-arithmetic",
	"sp-statement-store",
	"pallet-statement",
	"sp-authority-discovery",
	"pallet-session",
]}

native-api.workspace = true
pallet-commitments.workspace = true
pallet-permissions.workspace = true
pallet-tables.workspace = true
pallet-indexing.workspace = true
pallet-attestation.workspace = true
pallet-keystore.workspace = true
pallet-smartcontracts.workspace = true
pallet-zkpay.workspace = true
pallet-rewards.workspace = true
pallet-system-tables.workspace = true
pallet-system-contracts.workspace = true
proof-of-sql-commitment-map.workspace = true
sxt-core.workspace = true

[build-dependencies]
substrate-wasm-builder = { optional = true, workspace = true, default-features = true }

[features]
fast-runtime = []
default = ["std"]
std = [
	"polkadot-sdk/std",
	"pallet-smartcontracts/std",
	"native-api/std",
	"pallet-keystore/std",
	"pallet-attestation/std",
	"pallet-indexing/std",
	"pallet-tables/std",
	"pallet-permissions/std",
	"pallet-system-tables/std",
	"pallet-system-contracts/std",
	"pallet-zkpay/std",
	"codec/std",
	"scale-info/std",

	"substrate-wasm-builder",
	"proof-of-sql-commitment-map/std",
	"sxt-core/std",
	"eth-ecdsa/std",
]

runtime-benchmarks = [
	"polkadot-sdk/runtime-benchmarks",
	"pallet-keystore/runtime-benchmarks",
	"pallet-attestation/runtime-benchmarks",
	"pallet-indexing/runtime-benchmarks",
	"pallet-permissions/runtime-benchmarks",
	"eth-ecdsa/runtime-benchmarks",
	"pallet-system-contracts/runtime-benchmarks",
	"pallet-tables/runtime-benchmarks",
	"pallet-smartcontracts/runtime-benchmarks",
        "pallet-commitments/runtime-benchmarks",
        "native-api/runtime-benchmarks",
]

try-runtime = [
	"polkadot-sdk/try-runtime",
	"eth-ecdsa/try-runtime",
]

[lints]
workspace = true
