[package]
name = "pallet-commitments"
description = "Commitments pallet which manages proof-of-sql commitments."
version = "0.1.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = [
	"derive",
], workspace = true }
commitment-sql.workspace = true
commitment-column-mapping.workspace = true
scale-info = { features = [
	"derive",
], workspace = true }

polkadot-sdk = { workspace = true, features = [
	"frame-benchmarking", "frame-support", "frame-system",
	"sp-core", "sp-api", "sp-io", "sp-runtime",
]}

native-api.workspace = true
on-chain-table.workspace = true
proof-of-sql.workspace = true
proof-of-sql-commitment-map = { workspace = true, features = ["substrate"] }
proof-of-sql-static-setups = { workspace = true, features = ["baked"] }
sqlparser.workspace = true
sxt-core.workspace = true
snafu.workspace = true
itertools.workspace = true

clap = { workspace = true, optional = true, features = ["env", "derive"] }
tokio = { workspace = true, optional = true, features = ["rt-multi-thread"] }
env_logger = { workspace = true, optional = true }
log = { workspace = true, optional = true }

[dev-dependencies]
polkadot-sdk = { workspace = true, default-features = true, features = [
	"sp-core", "sp-io", "sp-runtime",
]}

[[bin]]
name = "test_end_row_limits"
required-features = ["test-end-row-limits"]

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"native-api/std",
	"polkadot-sdk/std",
]
runtime-benchmarks = [
	"polkadot-sdk/runtime-benchmarks",
]
try-runtime = [
	"polkadot-sdk/try-runtime",
]
test-end-row-limits = ["dep:clap", "proof-of-sql-static-setups/io", "dep:tokio", "dep:env_logger", "dep:log"]

[lints]
workspace = true
