
//! Autogenerated weights for `pallet_indexing`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2026-03-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `trevor-benchmark`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/sxt-node
// benchmark
// pallet
// --pallet
// pallet-indexing
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --template
// ./pallets/frame-weight-template.hbs
// --output
// ./pallets/indexing/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use polkadot_sdk::frame_system;
use core::marker::PhantomData;

/// Weight functions needed for `pallet_indexing`.
pub trait WeightInfo {
	fn submit_data_quorum_reached_dynamic_dory(c: u32, n: u32, ) -> Weight;
	fn submit_data_quorum_reached_hyper_kzg(c: u32, n: u32, ) -> Weight;
	fn set_block_number() -> Weight;
	fn submit_empty_blocks() -> Weight;
}

/// Weights for `pallet_indexing` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:0)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:0)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::FinalData` (r:2 w:1)
	/// Proof: `Indexing::FinalData` (`max_values`: None, `max_size`: Some(2337), added: 4812, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::Submissions` (r:2 w:1)
	/// Proof: `Indexing::Submissions` (`max_values`: None, `max_size`: Some(2151), added: 4626, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:1)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Tables::BlockEnforcement` (r:1 w:0)
	/// Proof: `Tables::BlockEnforcement` (`max_values`: None, `max_size`: Some(149), added: 2624, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 64]`.
	fn submit_data_quorum_reached_dynamic_dory(c: u32, _n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `40036`
		//  Estimated: `276827554`
		// Minimum execution time: 2_197_536_000 picoseconds.
		Weight::from_parts(27_450_900_711, 276827554)
			// Standard Error: 12_741_758
			.saturating_add(Weight::from_parts(2_125_268_905, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:0)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:0)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::FinalData` (r:2 w:1)
	/// Proof: `Indexing::FinalData` (`max_values`: None, `max_size`: Some(2337), added: 4812, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::Submissions` (r:2 w:1)
	/// Proof: `Indexing::Submissions` (`max_values`: None, `max_size`: Some(2151), added: 4626, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:1)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Tables::BlockEnforcement` (r:1 w:0)
	/// Proof: `Tables::BlockEnforcement` (`max_values`: None, `max_size`: Some(149), added: 2624, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 64]`.
	fn submit_data_quorum_reached_hyper_kzg(c: u32, _n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6752`
		//  Estimated: `276827554`
		// Minimum execution time: 919_598_000 picoseconds.
		Weight::from_parts(975_062_000, 276827554)
			// Standard Error: 2_447_500
			.saturating_add(Weight::from_parts(1_279_835_167, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Indexing::BlockNumbers` (r:0 w:1)
	/// Proof: `Indexing::BlockNumbers` (`max_values`: None, `max_size`: Some(156), added: 2631, mode: `MaxEncodedLen`)
	fn set_block_number() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_073_000 picoseconds.
		Weight::from_parts(7_334_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:0)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:0)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::FinalData` (r:2 w:1)
	/// Proof: `Indexing::FinalData` (`max_values`: None, `max_size`: Some(2337), added: 4812, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::Submissions` (r:2 w:1)
	/// Proof: `Indexing::Submissions` (`max_values`: None, `max_size`: Some(2151), added: 4626, mode: `MaxEncodedLen`)
	/// Storage: `Tables::BlockEnforcement` (r:1 w:0)
	/// Proof: `Tables::BlockEnforcement` (`max_values`: None, `max_size`: Some(149), added: 2624, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::BlockNumbers` (r:1 w:1)
	/// Proof: `Indexing::BlockNumbers` (`max_values`: None, `max_size`: Some(156), added: 2631, mode: `MaxEncodedLen`)
	fn submit_empty_blocks() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1110`
		//  Estimated: `276827554`
		// Minimum execution time: 117_319_000 picoseconds.
		Weight::from_parts(118_311_000, 276827554)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:0)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:0)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::FinalData` (r:2 w:1)
	/// Proof: `Indexing::FinalData` (`max_values`: None, `max_size`: Some(2337), added: 4812, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::Submissions` (r:2 w:1)
	/// Proof: `Indexing::Submissions` (`max_values`: None, `max_size`: Some(2151), added: 4626, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:1)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Tables::BlockEnforcement` (r:1 w:0)
	/// Proof: `Tables::BlockEnforcement` (`max_values`: None, `max_size`: Some(149), added: 2624, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 64]`.
	fn submit_data_quorum_reached_dynamic_dory(c: u32, _n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `40036`
		//  Estimated: `276827554`
		// Minimum execution time: 2_197_536_000 picoseconds.
		Weight::from_parts(27_450_900_711, 276827554)
			// Standard Error: 12_741_758
			.saturating_add(Weight::from_parts(2_125_268_905, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:0)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:0)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::FinalData` (r:2 w:1)
	/// Proof: `Indexing::FinalData` (`max_values`: None, `max_size`: Some(2337), added: 4812, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::Submissions` (r:2 w:1)
	/// Proof: `Indexing::Submissions` (`max_values`: None, `max_size`: Some(2151), added: 4626, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:1)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Tables::BlockEnforcement` (r:1 w:0)
	/// Proof: `Tables::BlockEnforcement` (`max_values`: None, `max_size`: Some(149), added: 2624, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 64]`.
	fn submit_data_quorum_reached_hyper_kzg(c: u32, _n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6752`
		//  Estimated: `276827554`
		// Minimum execution time: 919_598_000 picoseconds.
		Weight::from_parts(975_062_000, 276827554)
			// Standard Error: 2_447_500
			.saturating_add(Weight::from_parts(1_279_835_167, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Indexing::BlockNumbers` (r:0 w:1)
	/// Proof: `Indexing::BlockNumbers` (`max_values`: None, `max_size`: Some(156), added: 2631, mode: `MaxEncodedLen`)
	fn set_block_number() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_073_000 picoseconds.
		Weight::from_parts(7_334_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:0)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:0)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::FinalData` (r:2 w:1)
	/// Proof: `Indexing::FinalData` (`max_values`: None, `max_size`: Some(2337), added: 4812, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::Submissions` (r:2 w:1)
	/// Proof: `Indexing::Submissions` (`max_values`: None, `max_size`: Some(2151), added: 4626, mode: `MaxEncodedLen`)
	/// Storage: `Tables::BlockEnforcement` (r:1 w:0)
	/// Proof: `Tables::BlockEnforcement` (`max_values`: None, `max_size`: Some(149), added: 2624, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::BlockNumbers` (r:1 w:1)
	/// Proof: `Indexing::BlockNumbers` (`max_values`: None, `max_size`: Some(156), added: 2631, mode: `MaxEncodedLen`)
	fn submit_empty_blocks() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1110`
		//  Estimated: `276827554`
		// Minimum execution time: 117_319_000 picoseconds.
		Weight::from_parts(118_311_000, 276827554)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
