
//! Autogenerated weights for `pallet_indexing`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-12-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `trevor-benchmark`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/sxt-node
// benchmark
// pallet
// --pallet
// pallet_indexing
// --extrinsic
// *
// --steps=50
// --external-repeat=20
// --wasm-execution=compiled
// --template
// ./pallets/frame-weight-template.hbs
// --output
// ./pallets/indexing/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_indexing`.
pub trait WeightInfo {
	fn submit_data_quorum_not_reached() -> Weight;
	fn submit_data_quorum_reached() -> Weight;
}

/// Weights for `pallet_indexing` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:0)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:0)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::FinalData` (r:2 w:0)
	/// Proof: `Indexing::FinalData` (`max_values`: None, `max_size`: Some(2337), added: 4812, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::SubmissionsV1` (r:2 w:1)
	/// Proof: `Indexing::SubmissionsV1` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::BatchQueueBottom` (r:1 w:0)
	/// Proof: `Indexing::BatchQueueBottom` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::CounterForBatchQueue` (r:1 w:1)
	/// Proof: `Indexing::CounterForBatchQueue` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::BatchQueue` (r:1 w:1)
	/// Proof: `Indexing::BatchQueue` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn submit_data_quorum_not_reached() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1086`
		//  Estimated: `276827554`
		// Minimum execution time: 393_946_000 picoseconds.
		Weight::from_parts(396_661_000, 276827554)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:0)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:0)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::FinalData` (r:2 w:1)
	/// Proof: `Indexing::FinalData` (`max_values`: None, `max_size`: Some(2337), added: 4812, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::SubmissionsV1` (r:5 w:4)
	/// Proof: `Indexing::SubmissionsV1` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	fn submit_data_quorum_reached() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `46691`
		//  Estimated: `276827554`
		// Minimum execution time: 121_523_547_000 picoseconds.
		Weight::from_parts(125_296_478_000, 276827554)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:0)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:0)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::FinalData` (r:2 w:0)
	/// Proof: `Indexing::FinalData` (`max_values`: None, `max_size`: Some(2337), added: 4812, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::SubmissionsV1` (r:2 w:1)
	/// Proof: `Indexing::SubmissionsV1` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::BatchQueueBottom` (r:1 w:0)
	/// Proof: `Indexing::BatchQueueBottom` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::CounterForBatchQueue` (r:1 w:1)
	/// Proof: `Indexing::CounterForBatchQueue` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::BatchQueue` (r:1 w:1)
	/// Proof: `Indexing::BatchQueue` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn submit_data_quorum_not_reached() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1086`
		//  Estimated: `276827554`
		// Minimum execution time: 393_946_000 picoseconds.
		Weight::from_parts(396_661_000, 276827554)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:0)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:0)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::FinalData` (r:2 w:1)
	/// Proof: `Indexing::FinalData` (`max_values`: None, `max_size`: Some(2337), added: 4812, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::SubmissionsV1` (r:5 w:4)
	/// Proof: `Indexing::SubmissionsV1` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	fn submit_data_quorum_reached() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `46691`
		//  Estimated: `276827554`
		// Minimum execution time: 121_523_547_000 picoseconds.
		Weight::from_parts(125_296_478_000, 276827554)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
}
