
//! Autogenerated weights for `pallet_system_contracts`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-10-31, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `trevor-benchmark`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/sxt-node
// benchmark
// pallet
// --pallet
// pallet-system-contracts
// --extrinsic
// *
// --steps=50
// --external-repeat=20
// --wasm-execution=compiled
// --template
// ./pallets/frame-weight-template.hbs
// --output
// ./pallets/system-contracts/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_system_contracts`.
pub trait WeightInfo {
	fn set_staking_contract() -> Weight;
	fn set_messaging_contract() -> Weight;
}

/// Weights for `pallet_system_contracts` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SystemContracts::StakingContract` (r:0 w:1)
	/// Proof: `SystemContracts::StakingContract` (`max_values`: Some(1), `max_size`: Some(52), added: 547, mode: `MaxEncodedLen`)
	fn set_staking_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_818_000 picoseconds.
		Weight::from_parts(10_579_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SystemContracts::MessagingContract` (r:0 w:1)
	/// Proof: `SystemContracts::MessagingContract` (`max_values`: Some(1), `max_size`: Some(52), added: 547, mode: `MaxEncodedLen`)
	fn set_messaging_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_938_000 picoseconds.
		Weight::from_parts(10_610_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `SystemContracts::StakingContract` (r:0 w:1)
	/// Proof: `SystemContracts::StakingContract` (`max_values`: Some(1), `max_size`: Some(52), added: 547, mode: `MaxEncodedLen`)
	fn set_staking_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_818_000 picoseconds.
		Weight::from_parts(10_579_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `SystemContracts::MessagingContract` (r:0 w:1)
	/// Proof: `SystemContracts::MessagingContract` (`max_values`: Some(1), `max_size`: Some(52), added: 547, mode: `MaxEncodedLen`)
	fn set_messaging_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_938_000 picoseconds.
		Weight::from_parts(10_610_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
