-- CREATE SCHEMA IF NOT EXISTS ETHEREUM;
CREATE TABLE IF NOT EXISTS ETHEREUM.BLOCKS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    BLOCK_HASH BINARY NOT NULL,
    GAS_LIMIT DECIMAL(75, 0) NOT NULL,
    GAS_USED DECIMAL(75, 0) NOT NULL,
    MINER BINARY NOT NULL,
    PARENT_HASH BINARY NOT NULL,
    REWARD DECIMAL(75, 0) NOT NULL,
    SIZE BIGINT NOT NULL,
    TRANSACTION_COUNT INT NOT NULL,
    NONCE BINARY NOT NULL,
    RECEIPTS_ROOT BINARY NOT NULL,
    SHA3_UNCLES BINARY NOT NULL,
    STATE_ROOT BINARY NOT NULL,
    TRANSACTIONS_ROOT BINARY NOT NULL,
    UNCLES_COUNT BIGINT NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER)
);

CREATE TABLE IF NOT EXISTS ETHEREUM.TRANSACTIONS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    TRANSACTION_FEE DECIMAL(75, 0) NOT NULL,
    FROM_ADDRESS BINARY NOT NULL,
    TO_ADDRESS BINARY NOT NULL,
    VALUE_ DECIMAL(75, 0) NOT NULL,
    GAS BIGINT NOT NULL,
    RECEIPT_CUMULATIVE_GAS_USED BIGINT NOT NULL,
    RECEIPT_STATUS BOOLEAN NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, TRANSACTION_HASH)
);

CREATE TABLE IF NOT EXISTS ETHEREUM.TRANSACTION_DETAILS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    METHOD_ID BINARY NOT NULL,
    RECEIPT_CONTRACT_ADDRESS ADDRESS NOT NULL,
    TYPE_ INT NOT NULL,
    GAS_PRICE DECIMAL(75, 0) NOT NULL,
    NONCE INT NOT NULL,
    RECEIPT_GAS_USED INT NOT NULL,
    MAX_FEE_PER_GAS DECIMAL(75, 0) NOT NULL,
    MAX_PRIORITY_FEE_PER_GAS DECIMAL(75, 0) NOT NULL,
    RECEIPT_EFFECTIVE_GAS_PRICE DECIMAL(75, 0) NOT NULL,
    LOGS_COUNT INT NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, TRANSACTION_HASH)
);

CREATE TABLE IF NOT EXISTS ETHEREUM.NATIVE_WALLETS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    WALLET_ADDRESS ADDRESS NOT NULL,
    BALANCE DECIMAL(75, 0) NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, WALLET_ADDRESS, BALANCE)
);

CREATE TABLE IF NOT EXISTS ETHEREUM.NATIVE_TOKEN_TRANSFERS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    FROM_ ADDRESS NOT NULL,
    TO_ ADDRESS NOT NULL,
    VALUE_ DECIMAL(75, 0) NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, TRANSACTION_HASH)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.CONTRACTS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    CONTRACT_CREATOR_ADDRESS ADDRESS NOT NULL,
    PRIMARY KEY (CONTRACT_ADDRESS, TRANSACTION_HASH)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.TOKEN_ERC20_CONTRACTS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    NAME VARCHAR NOT NULL,
    SYMBOL VARCHAR NOT NULL,
    DECIMALS SMALLINT NOT NULL,
    PRIMARY KEY (TRANSACTION_HASH, CONTRACT_ADDRESS)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.TOKEN_ERC20_TRANSFERS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    FROM_ ADDRESS NOT NULL,
    TO_ ADDRESS NOT NULL,
    VALUE_ DECIMAL(75, 0) NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.NFT_ERC721_CONTRACTS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    NAME VARCHAR NOT NULL,
    SYMBOL VARCHAR NOT NULL,
    PRIMARY KEY (TRANSACTION_HASH, CONTRACT_ADDRESS)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.NFT_ERC1155_CONTRACTS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    PRIMARY KEY (TRANSACTION_HASH, CONTRACT_ADDRESS)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.NFT_ERC1155_TRANSFER (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    OPERATOR ADDRESS NOT NULL,
    FROM_ ADDRESS NOT NULL,
    TO_ ADDRESS NOT NULL,
    ID BINARY NOT NULL,
    VALUE_ DECIMAL(75, 0) NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.NFT_ERC721_APPROVAL (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    OWNER ADDRESS NOT NULL,
    APPROVED ADDRESS NOT NULL,
    TOKEN_ID BINARY NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.NFT_ERC721_APPROVAL_FOR_ALL (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    OWNER ADDRESS NOT NULL,
    OPERATOR ADDRESS NOT NULL,
    APPROVED BOOLEAN NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.NFT_ERC721_TRANSFER (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    FROM_ ADDRESS NOT NULL,
    TO_ ADDRESS NOT NULL,
    TOKEN_ID BINARY NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.ERC173_OWNERSHIP_TRANSFERRED (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    PREVIOUS_OWNER ADDRESS NOT NULL,
    NEW_OWNER ADDRESS NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.PROXY_ERC1967_UPGRADES (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    EVENT_INDEX INT NOT NULL,
    PROXY_CONTRACT ADDRESS NOT NULL,
    IMPLEMENTATION_CONTRACT ADDRESS NOT NULL,
    PRIMARY KEY (TRANSACTION_HASH, EVENT_INDEX)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.PROXY_ERC1967_ADMIN_CHANGES (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    EVENT_INDEX INT NOT NULL,
    PROXY_CONTRACT ADDRESS NOT NULL,
    PREVIOUS_ADMIN ADDRESS NOT NULL,
    NEW_ADMIN ADDRESS NOT NULL,
    PRIMARY KEY (TRANSACTION_HASH, EVENT_INDEX)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.PROXY_NON_ERC_UPGRADES (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    EVENT_INDEX INT NOT NULL,
    PROXY_CONTRACT ADDRESS NOT NULL,
    IMPLEMENTATION_CONTRACT ADDRESS NOT NULL,
    PRIMARY KEY (TRANSACTION_HASH, EVENT_INDEX)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.TOKEN_ERC20_WALLET_BALANCES (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    WALLET_ADDRESS ADDRESS NOT NULL,
    TOKEN_ADDRESS ADDRESS NOT NULL,
    BALANCE DECIMAL(75, 0) NOT NULL,
    PRIMARY KEY (
                    BLOCK_NUMBER,
                    WALLET_ADDRESS,
                    TOKEN_ADDRESS,
                    BALANCE
                )
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.TOKEN_ERC20_APPROVAL (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    OWNER ADDRESS NOT NULL,
    SPENDER ADDRESS NOT NULL,
    VALUE_ DECIMAL(75, 0) NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.NFT_ERC721_OWNERS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    TOKEN_ID BINARY NOT NULL,
    OWNER ADDRESS NOT NULL,
    BALANCE DECIMAL(75, 0) NOT NULL,
    PRIMARY KEY (
                    BLOCK_NUMBER,
                    CONTRACT_ADDRESS,
                    TOKEN_ID,
                    OWNER,
                    BALANCE
                )
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.NFT_ERC1155_OWNERS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    OWNER ADDRESS NOT NULL,
    TOKEN_ID BINARY NOT NULL,
    BALANCE DECIMAL(75, 0) NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, CONTRACT_ADDRESS, OWNER, TOKEN_ID)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.LOGS (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS ADDRESS NOT NULL,
    TOPIC_0 BINARY,
    TOPIC_1 BINARY,
    TOPIC_2 BINARY,
    TOPIC_3 BINARY,
    STATUS BOOLEAN,
    RAW_DATA VARCHAR NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, TRANSACTION_HASH, EVENT_INDEX)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.STORAGE_SLOT_UPDATES (
    BLOCK_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    TRANSACTION_HASH VARCHAR NOT NULL,
    TRANSACTION_INDEX INT NOT NULL,
    CONTRACT_ADDRESS VARCHAR NOT NULL,
    SLOT_POSITION VARCHAR NOT NULL,
    SLOT_VALUE VARCHAR,
    PRIMARY KEY (BLOCK_NUMBER, CONTRACT_ADDRESS)
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";

CREATE TABLE IF NOT EXISTS ETHEREUM.SXT_VALUE_OVERFLOW (
    TIME_STAMP TIMESTAMP NOT NULL,
    BLOCK_NUMBER BIGINT NOT NULL,
    TRANSACTION_HASH BINARY,
    TRANSACTION_INDEX INT,
    SCHEMA VARCHAR NOT NULL,
    TABLE_NAME VARCHAR NOT NULL,
    COLUMN_NAME VARCHAR NOT NULL,
    ORIGINAL_VALUE VARCHAR NOT NULL,
    PRIMARY KEY (
        BLOCK_NUMBER,
        TRANSACTION_HASH,
        TRANSACTION_INDEX,
        SCHEMA,
        TABLE_NAME,
        COLUMN_NAME,
        ORIGINAL_VALUE
    )
) WITH "AFFINITY_KEY=TODO,TEMPLATE=deltastore,public_key=d088d3cdfc56cec28bbefa467a1e37207a44c698d532d7bd65b5dead98214484,columnar_storage=true,immutable=true,access_type=public_read,cdcEnabled=false,partition_cols=year(TIME_STAMP)|month(TIME_STAMP),CACHE_INTERNAL_ID=ffffffff-ffff-ffff-ffff-ffffffffffff,data_region=external";