[package]
name = "proof-of-sql-commitment-map"
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
itertools = { workspace = true }
proof-of-sql = { workspace = true }
curve25519-dalek = { workspace = true }
snafu = { workspace = true }

[features]
memory-commitment-map = []

[dev-dependencies]
proof-of-sql = { workspace = true, features = ["test"] }
proof-of-sql-parser = { workspace = true }
fake = { workspace = true }
