[package]
name = "proof-of-sql-commitment-map"
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]

polkadot-sdk = { workspace = true, features = ["sp-core", "sp-runtime-interface", "frame-support", "frame-system",], optional = true}
# Required for the PassByCodec derive macro to work
sp-runtime-interface = { workspace = true , optional = true, default-features = false }

bincode = { workspace = true, features = ["serde", "alloc"], optional = true }
codec = { workspace = true, features = ["derive"], optional = true }
curve25519-dalek = { workspace = true }
itertools = { workspace = true }
proof-of-sql = { workspace = true }
scale-info = { workspace = true, features = ["derive"], optional = true }
serde = { workspace = true }
snafu = { workspace = true }
sxt-core = { workspace = true, optional = true }
proptest = { workspace = true, features = ["std"], optional = true }
proptest-derive = { workspace = true, optional = true }
proof-of-sql-unchecked-deserialize.workspace = true

[features]
memory-commitment-map = ["std"]
substrate = ["dep:codec", "dep:scale-info", "dep:sxt-core", "dep:bincode", "dep:polkadot-sdk", "dep:sp-runtime-interface",]
std = []
try-runtime = []
proptest = ["dep:proptest", "dep:proptest-derive", "std"]

[dev-dependencies]
rand_chacha.workspace = true
proof-of-sql = { workspace = true, features = ["test"] }
rand.workspace = true
on-chain-table = { workspace = true }
sxt-core = { workspace = true, features = ["std"] }
sqlparser = { workspace = true }

[lints]
workspace = true

[[example]]
name = "pallet"
required-features = ["substrate", "std"]
crate-type = ["staticlib"]
