[package]
name = "native"
description = "Provide a native implementation bridge for wasm executor"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
codec = { workspace = true }
commitment-sql = { workspace = true, optional = true, features = ["cpu-perf"] }
log = "0.4.11"

polkadot-sdk = { workspace = true, features = [
	"sp-runtime-interface", "sp-runtime", "frame-support", 
	"frame-benchmarking", "frame-system", "sp-core",
]}

# Required for the Native runtime_interface macro to work
sp-runtime-interface = { workspace = true }

on-chain-table = { workspace = true, default-features = false, features = ["arrow"], optional=true}
scale-info = { workspace = true, default-features = false, features = ["derive"] }
tonic = { workspace = true, optional = true }
arrow = { workspace = true, optional = true, features = ["ipc"]}
proof-of-sql-commitment-map = { workspace = true, features = ["substrate"] }
proof-of-sql-static-setups = { workspace = true, optional = true, features = ["io"] }
futures = { features = ["thread-pool"], workspace = true, optional = true }
proptest = { workspace = true, optional = true, features = ["std"] }

hex = { workspace = true, optional = true }

sxt-core.workspace = true
proof-of-sql = { workspace = true, optional = true }
clap = { workspace = true, optional = true, features = ["env", "derive"] }

[dev-dependencies]
proof-of-sql = { workspace = true }
sqlparser.workspace = true
rayon.workspace = true

[[bin]]
name = "generate-backwards-compatibility-cases"
required-features = ["generate_backwards_compatibility_cases"]

[features]
default = ["std"]
std = [
    "polkadot-sdk/std",
    "sp-runtime-interface/std",
    "codec/std",
    "dep:arrow", # <------- put std dependencies here
    "dep:commitment-sql",
    "dep:on-chain-table",
    "dep:proof-of-sql-static-setups",
    "dep:tonic",
    "dep:futures",
    "dep:proof-of-sql",
    "sxt-core/std",
]
generate_backwards_compatibility_cases = ["std", "dep:proptest", "dep:hex", "sxt-core/proptest", "proof-of-sql-commitment-map/proptest", "commitment-sql/proptest", "dep:proof-of-sql", "dep:clap"]

[target.'cfg(not(target_arch = "aarch64"))'.dependencies]
proof-of-sql = { workspace = true, optional = true, features = ["cpu-perf"] }
