[package]
name = "native-pallets"
version = "0.1.0"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
pallet-indexing.workspace = true
native-api.workspace = true
native.workspace = true
sxt-core.workspace = true

[features]
default = ["std"]
std = [
    "native-api/std",
    "native/std",

    "sxt-core/std",
    "pallet-indexing/std",
]
try-runtime = []
