[package]
name = "pallet-system-tables"
description = "Substrate pallet for parsing system information out of submitted data"
version = "0.1.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = [
	"derive",
], workspace = true }
scale-info = { features = [
	"derive",
], workspace = true }

polkadot-sdk = { workspace = true, features = [
	"frame-benchmarking", "frame-support", "frame-system", 
	"pallet-balances", "pallet-staking", "pallet-session", "pallet-offences", 
	"sp-staking", "sp-runtime", "sp-core", "sp-io", "sp-api",
	]}

pallet-zkpay.workspace = true
pallet-tables.workspace = true
sxt-core = { default-features = false, workspace = true }
on-chain-table = { workspace = true, default-features = false }
spin.workspace = true
hex.workspace = true
log.workspace = true
itertools.workspace = true

[dev-dependencies]
polkadot-sdk = { workspace = true, features = [
	"pallet-staking-reward-curve", "frame-election-provider-support", "pallet-authorship", 
	"pallet-timestamp", "pallet-staking", "pallet-balances", "pallet-babe", "pallet-grandpa", 
	"pallet-authority-discovery", "sp-authority-discovery", "sp-consensus-babe", 
	"sp-core", "sp-io", "sp-runtime",
	]}
pallet-commitments.workspace = true

proof-of-sql-static-setups = { workspace = true, features = ["io"] }
pallet-permissions.workspace = true
arrow = { workspace = true }
proof-of-sql-commitment-map.workspace = true
serde_json = { workspace = true, default-features = false, features = ["alloc"] }

[features]
default = ["std"]
std = [
	"codec/std",
	"polkadot-sdk/std",
	"scale-info/std",
	"pallet-tables/std",
	"pallet-commitments/std",
	"pallet-zkpay/std",
	"sxt-core/std",
	"on-chain-table/std",
	"pallet-permissions/std",
]

runtime-benchmarks = [
	"polkadot-sdk/runtime-benchmarks",
]
try-runtime = [
	"polkadot-sdk/try-runtime",
]

[lints]
workspace = true

