[package]
name = "data-compliance-please-deprecate-me"
version = "0.1.0"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
arrow = { workspace = true, optional = true }
bigdecimal = { workspace = true, optional = true }
sqlparser.workspace = true
indexmap = { workspace = true, optional = true, features = ["std"] }
num-bigint = { workspace = true, optional = true }
snafu = { workspace = true, optional = true }

[features]
std = ["dep:indexmap", "dep:snafu", "dep:bigdecimal", "dep:num-bigint", "dep:arrow"]

[lints]
workspace = true
