[package]
name = "data-compliance-please-deprecate-me"
version = "0.1.0"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
arrow.workspace = true
bigdecimal.workspace = true
sqlparser.workspace = true
indexmap = { workspace = true, features = ["std"] }
snafu.workspace = true

[lints]
workspace = true
