[package]
name = "attestation_tree"
version = "0.1.0"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
codec.workspace = true
impl-trait-for-tuples.workspace = true
frame-support = { workspace = true, features = ["std"] }

[dev-dependencies]
sp-core = { workspace = true, features = ["std"] }

[lints]
workspace = true
