[package]
name = "attestation_tree"
version = "0.1.0"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
polkadot-sdk = { workspace = true, features = [
	"pallet-balances", "frame-support",
]}
codec.workspace = true
hex.workspace = true
impl-trait-for-tuples.workspace = true
eth_merkle_tree.workspace = true
snafu.workspace = true
sxt-core = { workspace = true, features = ["std"] }
pallet-commitments = { workspace = true, features = ["std"] }
proof-of-sql-commitment-map = { workspace = true, features = ["std"] }

[dev-dependencies]
polkadot-sdk = { workspace = true, features = ["sp-core"] }
sxt-runtime = { workspace = true, features = ["std"] }

[lints]
workspace = true
