
//! Autogenerated weights for `pallet_smartcontracts`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-10-31, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `trevor-benchmark`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/sxt-node
// benchmark
// pallet
// --pallet
// pallet_smartcontracts
// --extrinsic
// *
// --steps=50
// --external-repeat=20
// --wasm-execution=compiled
// --template
// ./pallets/frame-weight-template.hbs
// --output
// ./pallets/smartcontracts/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use polkadot_sdk::frame_system;
use core::marker::PhantomData;

/// Weight functions needed for `pallet_smartcontracts`.
pub trait WeightInfo {
	fn add_smartcontract_zero_tables() -> Weight;
	fn add_smartcontract_one_table() -> Weight;
	fn remove_smartcontract_zero_tables() -> Weight;
	fn remove_smartcontract_one_table() -> Weight;
}

/// Weights for `pallet_smartcontracts` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Smartcontracts::ContractStorage` (r:1 w:1)
	/// Proof: `Smartcontracts::ContractStorage` (`max_values`: None, `max_size`: Some(229460), added: 231935, mode: `MaxEncodedLen`)
	/// Storage: `Tables::NamespaceVersions` (r:1 w:1)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `Smartcontracts::ContractTables` (r:0 w:1)
	/// Proof: `Smartcontracts::ContractTables` (`max_values`: None, `max_size`: Some(140455), added: 142930, mode: `MaxEncodedLen`)
	fn add_smartcontract_zero_tables() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `131`
		//  Estimated: `232925`
		// Minimum execution time: 76_844_000 picoseconds.
		Weight::from_parts(79_278_000, 232925)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:1)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Smartcontracts::ContractStorage` (r:1 w:1)
	/// Proof: `Smartcontracts::ContractStorage` (`max_values`: None, `max_size`: Some(229460), added: 231935, mode: `MaxEncodedLen`)
	/// Storage: `Tables::NamespaceVersions` (r:2 w:1)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableVersions` (r:1 w:1)
	/// Proof: `Tables::TableVersions` (`max_values`: None, `max_size`: Some(232), added: 2707, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Identifiers` (r:1 w:1)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::BlockNumbers` (r:0 w:1)
	/// Proof: `Indexing::BlockNumbers` (`max_values`: None, `max_size`: Some(156), added: 2631, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableSources` (r:0 w:1)
	/// Proof: `Tables::TableSources` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:0 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Tables::ColumnVersions` (r:0 w:1)
	/// Proof: `Tables::ColumnVersions` (`max_values`: None, `max_size`: Some(8616), added: 11091, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableOwners` (r:0 w:1)
	/// Proof: `Tables::TableOwners` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:0 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Smartcontracts::ContractTables` (r:0 w:1)
	/// Proof: `Smartcontracts::ContractTables` (`max_values`: None, `max_size`: Some(140455), added: 142930, mode: `MaxEncodedLen`)
	fn add_smartcontract_one_table() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `259`
		//  Estimated: `276827554`
		// Minimum execution time: 2_772_751_000 picoseconds.
		Weight::from_parts(2_809_738_000, 276827554)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(14_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Smartcontracts::ContractTables` (r:1 w:1)
	/// Proof: `Smartcontracts::ContractTables` (`max_values`: None, `max_size`: Some(140455), added: 142930, mode: `MaxEncodedLen`)
	/// Storage: `Smartcontracts::ContractStorage` (r:0 w:1)
	/// Proof: `Smartcontracts::ContractStorage` (`max_values`: None, `max_size`: Some(229460), added: 231935, mode: `MaxEncodedLen`)
	fn remove_smartcontract_zero_tables() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `295`
		//  Estimated: `143920`
		// Minimum execution time: 31_759_000 picoseconds.
		Weight::from_parts(32_681_000, 143920)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Smartcontracts::ContractTables` (r:1 w:1)
	/// Proof: `Smartcontracts::ContractTables` (`max_values`: None, `max_size`: Some(140455), added: 142930, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Identifiers` (r:1 w:1)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Snapshots` (r:1 w:0)
	/// Proof: `Tables::Snapshots` (`max_values`: None, `max_size`: Some(2198), added: 4673, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableSources` (r:1 w:1)
	/// Proof: `Tables::TableSources` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableOwners` (r:1 w:1)
	/// Proof: `Tables::TableOwners` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:3 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Smartcontracts::ContractStorage` (r:0 w:1)
	/// Proof: `Smartcontracts::ContractStorage` (`max_values`: None, `max_size`: Some(229460), added: 231935, mode: `MaxEncodedLen`)
	fn remove_smartcontract_one_table() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `46030`
		//  Estimated: `276827554`
		// Minimum execution time: 159_187_000 picoseconds.
		Weight::from_parts(162_173_000, 276827554)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Smartcontracts::ContractStorage` (r:1 w:1)
	/// Proof: `Smartcontracts::ContractStorage` (`max_values`: None, `max_size`: Some(229460), added: 231935, mode: `MaxEncodedLen`)
	/// Storage: `Tables::NamespaceVersions` (r:1 w:1)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `Smartcontracts::ContractTables` (r:0 w:1)
	/// Proof: `Smartcontracts::ContractTables` (`max_values`: None, `max_size`: Some(140455), added: 142930, mode: `MaxEncodedLen`)
	fn add_smartcontract_zero_tables() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `131`
		//  Estimated: `232925`
		// Minimum execution time: 76_844_000 picoseconds.
		Weight::from_parts(79_278_000, 232925)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:1)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Smartcontracts::ContractStorage` (r:1 w:1)
	/// Proof: `Smartcontracts::ContractStorage` (`max_values`: None, `max_size`: Some(229460), added: 231935, mode: `MaxEncodedLen`)
	/// Storage: `Tables::NamespaceVersions` (r:2 w:1)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableVersions` (r:1 w:1)
	/// Proof: `Tables::TableVersions` (`max_values`: None, `max_size`: Some(232), added: 2707, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Identifiers` (r:1 w:1)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Indexing::BlockNumbers` (r:0 w:1)
	/// Proof: `Indexing::BlockNumbers` (`max_values`: None, `max_size`: Some(156), added: 2631, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableSources` (r:0 w:1)
	/// Proof: `Tables::TableSources` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:0 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Tables::ColumnVersions` (r:0 w:1)
	/// Proof: `Tables::ColumnVersions` (`max_values`: None, `max_size`: Some(8616), added: 11091, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableOwners` (r:0 w:1)
	/// Proof: `Tables::TableOwners` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:0 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Smartcontracts::ContractTables` (r:0 w:1)
	/// Proof: `Smartcontracts::ContractTables` (`max_values`: None, `max_size`: Some(140455), added: 142930, mode: `MaxEncodedLen`)
	fn add_smartcontract_one_table() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `259`
		//  Estimated: `276827554`
		// Minimum execution time: 2_772_751_000 picoseconds.
		Weight::from_parts(2_809_738_000, 276827554)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(14_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Smartcontracts::ContractTables` (r:1 w:1)
	/// Proof: `Smartcontracts::ContractTables` (`max_values`: None, `max_size`: Some(140455), added: 142930, mode: `MaxEncodedLen`)
	/// Storage: `Smartcontracts::ContractStorage` (r:0 w:1)
	/// Proof: `Smartcontracts::ContractStorage` (`max_values`: None, `max_size`: Some(229460), added: 231935, mode: `MaxEncodedLen`)
	fn remove_smartcontract_zero_tables() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `295`
		//  Estimated: `143920`
		// Minimum execution time: 31_759_000 picoseconds.
		Weight::from_parts(32_681_000, 143920)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Smartcontracts::ContractTables` (r:1 w:1)
	/// Proof: `Smartcontracts::ContractTables` (`max_values`: None, `max_size`: Some(140455), added: 142930, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Identifiers` (r:1 w:1)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Snapshots` (r:1 w:0)
	/// Proof: `Tables::Snapshots` (`max_values`: None, `max_size`: Some(2198), added: 4673, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableSources` (r:1 w:1)
	/// Proof: `Tables::TableSources` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableOwners` (r:1 w:1)
	/// Proof: `Tables::TableOwners` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:3 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Smartcontracts::ContractStorage` (r:0 w:1)
	/// Proof: `Smartcontracts::ContractStorage` (`max_values`: None, `max_size`: Some(229460), added: 231935, mode: `MaxEncodedLen`)
	fn remove_smartcontract_one_table() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `46030`
		//  Estimated: `276827554`
		// Minimum execution time: 159_187_000 picoseconds.
		Weight::from_parts(162_173_000, 276827554)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
}
