[package]
name = "eth-ecdsa"
version = "0.1.0"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["k256"] }
codec = { features = [
	"derive",
], workspace = true }
k256 = { workspace = true }
scale-info = { features = [
	"derive",
	"serde",
], workspace = true }
sp-core = { features = ["serde"], workspace = true }
sp-io = { workspace = true }
sp-runtime = { features = ["serde"], workspace = true }
serde = { workspace = true, optional = true }
snafu = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
sp-runtime = { features = ["serde"], workspace = true }

[features]
serde = ["dep:serde"]
std = [
	"codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
]

runtime-benchmarks = [
	"sp-runtime/runtime-benchmarks",
]

try-runtime = [
	"sp-runtime/try-runtime",
]

[lints]
workspace = true
