[package]
name = "eth-ecdsa"
version = "0.1.0"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["k256"] }
codec = { features = [
	"derive",
], workspace = true }
k256 = { workspace = true }
scale-info = { features = [
	"derive",
	"serde",
], workspace = true }

polkadot-sdk = { workspace = true, features = [
	"sp-core", "sp-io", "sp-runtime",
]}

serde = { workspace = true, optional = true }
snafu = { workspace = true }

[dev-dependencies]
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }

[features]
serde = ["dep:serde"]
std = [
	"polkadot-sdk/std",
	"codec/std",
	"scale-info/std",
]

runtime-benchmarks = [
	"polkadot-sdk/runtime-benchmarks",
]

try-runtime = [
	"polkadot-sdk/try-runtime",
]

[lints]
workspace = true
