
//! Autogenerated weights for `pallet_tables`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2026-03-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `trevor-benchmark`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/sxt-node
// benchmark
// pallet
// --pallet
// pallet-tables
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --template
// ./pallets/frame-weight-template.hbs
// --output
// ./pallets/tables/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use polkadot_sdk::frame_system;
use core::marker::PhantomData;

/// Weight functions needed for `pallet_tables`.
pub trait WeightInfo {
	fn create_zero_tables() -> Weight;
	fn create_one_table() -> Weight;
	fn clear_tables() -> Weight;
	fn create_namespace() -> Weight;
	fn drop_table() -> Weight;
	fn drop_invalid_commits() -> Weight;
	fn update_namespace_uuid() -> Weight;
	fn update_table_uuid() -> Weight;
	fn update_table_quorum() -> Weight;
	fn update_schema_quorum() -> Weight;
	fn set_block_enforcement() -> Weight;
	fn set_table_metadata() -> Weight;
	fn create_table_with_sci_metadata() -> Weight;
}

/// Weights for `pallet_tables` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_zero_tables() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `81`
		//  Estimated: `3546`
		// Minimum execution time: 17_673_000 picoseconds.
		Weight::from_parts(18_304_000, 3546)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::NamespaceVersions` (r:1 w:0)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableVersions` (r:1 w:1)
	/// Proof: `Tables::TableVersions` (`max_values`: None, `max_size`: Some(232), added: 2707, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Identifiers` (r:1 w:1)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1024 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableSources` (r:0 w:1)
	/// Proof: `Tables::TableSources` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:0 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Tables::ColumnVersions` (r:0 w:1)
	/// Proof: `Tables::ColumnVersions` (`max_values`: None, `max_size`: Some(8616), added: 11091, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableOwners` (r:0 w:1)
	/// Proof: `Tables::TableOwners` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	fn create_one_table() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `110046`
		//  Estimated: `276827554`
		// Minimum execution time: 6_603_977_000 picoseconds.
		Weight::from_parts(6_705_197_000, 276827554)
			.saturating_add(T::DbWeight::get().reads(1030_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: `Tables::Schemas` (r:500 w:500)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:500 w:500)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:1000 w:1000)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	fn clear_tables() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `124323`
		//  Estimated: `47972990`
		// Minimum execution time: 3_830_084_000 picoseconds.
		Weight::from_parts(3_883_236_000, 47972990)
			.saturating_add(T::DbWeight::get().reads(2000_u64))
			.saturating_add(T::DbWeight::get().writes(2000_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::NamespaceVersions` (r:1 w:1)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	fn create_namespace() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `87`
		//  Estimated: `3631`
		// Minimum execution time: 46_076_000 picoseconds.
		Weight::from_parts(46_717_000, 3631)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:1)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Snapshots` (r:1 w:0)
	/// Proof: `Tables::Snapshots` (`max_values`: None, `max_size`: Some(2198), added: 4673, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableSources` (r:1 w:1)
	/// Proof: `Tables::TableSources` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableOwners` (r:1 w:1)
	/// Proof: `Tables::TableOwners` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:3 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	fn drop_table() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45741`
		//  Estimated: `276827554`
		// Minimum execution time: 139_029_000 picoseconds.
		Weight::from_parts(140_493_000, 276827554)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `Commitments::CommitmentStorageMap` (r:3 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	fn drop_invalid_commits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45109`
		//  Estimated: `144906`
		// Minimum execution time: 72_616_000 picoseconds.
		Weight::from_parts(73_137_000, 144906)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::NamespaceVersions` (r:1 w:1)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	fn update_namespace_uuid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `189`
		//  Estimated: `3654`
		// Minimum execution time: 27_983_000 picoseconds.
		Weight::from_parts(28_613_000, 3654)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::TableVersions` (r:1 w:1)
	/// Proof: `Tables::TableVersions` (`max_values`: None, `max_size`: Some(232), added: 2707, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	fn update_table_uuid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3146`
		//  Estimated: `11823`
		// Minimum execution time: 933_646_000 picoseconds.
		Weight::from_parts(936_853_000, 11823)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	fn update_table_quorum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `368`
		//  Estimated: `3833`
		// Minimum execution time: 31_910_000 picoseconds.
		Weight::from_parts(32_471_000, 3833)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Schemas` (r:1025 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:1024 w:1024)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	fn update_schema_quorum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `132568`
		//  Estimated: `11104815`
		// Minimum execution time: 14_308_404_000 picoseconds.
		Weight::from_parts(14_572_079_000, 11104815)
			.saturating_add(T::DbWeight::get().reads(2050_u64))
			.saturating_add(T::DbWeight::get().writes(1024_u64))
	}
	/// Storage: `Tables::BlockEnforcement` (r:0 w:1)
	/// Proof: `Tables::BlockEnforcement` (`max_values`: None, `max_size`: Some(149), added: 2624, mode: `MaxEncodedLen`)
	fn set_block_enforcement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_033_000 picoseconds.
		Weight::from_parts(7_454_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Tables::TableMetadata` (r:0 w:1)
	/// Proof: `Tables::TableMetadata` (`max_values`: None, `max_size`: Some(8424), added: 10899, mode: `MaxEncodedLen`)
	fn set_table_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 13_005_000 picoseconds.
		Weight::from_parts(13_395_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::NamespaceVersions` (r:1 w:0)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableVersions` (r:1 w:1)
	/// Proof: `Tables::TableVersions` (`max_values`: None, `max_size`: Some(232), added: 2707, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Identifiers` (r:1 w:1)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1024 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableSources` (r:0 w:1)
	/// Proof: `Tables::TableSources` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:0 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Tables::ColumnVersions` (r:0 w:1)
	/// Proof: `Tables::ColumnVersions` (`max_values`: None, `max_size`: Some(8616), added: 11091, mode: `MaxEncodedLen`)
	/// Storage: `Tables::BlockEnforcement` (r:0 w:1)
	/// Proof: `Tables::BlockEnforcement` (`max_values`: None, `max_size`: Some(149), added: 2624, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableOwners` (r:0 w:1)
	/// Proof: `Tables::TableOwners` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableMetadata` (r:0 w:1)
	/// Proof: `Tables::TableMetadata` (`max_values`: None, `max_size`: Some(8424), added: 10899, mode: `MaxEncodedLen`)
	fn create_table_with_sci_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `110046`
		//  Estimated: `276827554`
		// Minimum execution time: 6_627_318_000 picoseconds.
		Weight::from_parts(6_700_695_000, 276827554)
			.saturating_add(T::DbWeight::get().reads(1030_u64))
			.saturating_add(T::DbWeight::get().writes(11_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_zero_tables() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `81`
		//  Estimated: `3546`
		// Minimum execution time: 17_673_000 picoseconds.
		Weight::from_parts(18_304_000, 3546)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::NamespaceVersions` (r:1 w:0)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableVersions` (r:1 w:1)
	/// Proof: `Tables::TableVersions` (`max_values`: None, `max_size`: Some(232), added: 2707, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Identifiers` (r:1 w:1)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1024 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableSources` (r:0 w:1)
	/// Proof: `Tables::TableSources` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:0 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Tables::ColumnVersions` (r:0 w:1)
	/// Proof: `Tables::ColumnVersions` (`max_values`: None, `max_size`: Some(8616), added: 11091, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableOwners` (r:0 w:1)
	/// Proof: `Tables::TableOwners` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	fn create_one_table() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `110046`
		//  Estimated: `276827554`
		// Minimum execution time: 6_603_977_000 picoseconds.
		Weight::from_parts(6_705_197_000, 276827554)
			.saturating_add(RocksDbWeight::get().reads(1030_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: `Tables::Schemas` (r:500 w:500)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:500 w:500)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:1000 w:1000)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	fn clear_tables() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `124323`
		//  Estimated: `47972990`
		// Minimum execution time: 3_830_084_000 picoseconds.
		Weight::from_parts(3_883_236_000, 47972990)
			.saturating_add(RocksDbWeight::get().reads(2000_u64))
			.saturating_add(RocksDbWeight::get().writes(2000_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::NamespaceVersions` (r:1 w:1)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	fn create_namespace() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `87`
		//  Estimated: `3631`
		// Minimum execution time: 46_076_000 picoseconds.
		Weight::from_parts(46_717_000, 3631)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Identifiers` (r:1 w:1)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Snapshots` (r:1 w:0)
	/// Proof: `Tables::Snapshots` (`max_values`: None, `max_size`: Some(2198), added: 4673, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableSources` (r:1 w:1)
	/// Proof: `Tables::TableSources` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableOwners` (r:1 w:1)
	/// Proof: `Tables::TableOwners` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:3 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	fn drop_table() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45741`
		//  Estimated: `276827554`
		// Minimum execution time: 139_029_000 picoseconds.
		Weight::from_parts(140_493_000, 276827554)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `Commitments::CommitmentStorageMap` (r:3 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	fn drop_invalid_commits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45109`
		//  Estimated: `144906`
		// Minimum execution time: 72_616_000 picoseconds.
		Weight::from_parts(73_137_000, 144906)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::NamespaceVersions` (r:1 w:1)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	fn update_namespace_uuid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `189`
		//  Estimated: `3654`
		// Minimum execution time: 27_983_000 picoseconds.
		Weight::from_parts(28_613_000, 3654)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::TableVersions` (r:1 w:1)
	/// Proof: `Tables::TableVersions` (`max_values`: None, `max_size`: Some(232), added: 2707, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	fn update_table_uuid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3146`
		//  Estimated: `11823`
		// Minimum execution time: 933_646_000 picoseconds.
		Weight::from_parts(936_853_000, 11823)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::TableInsertQuorums` (r:1 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	fn update_table_quorum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `368`
		//  Estimated: `3833`
		// Minimum execution time: 31_910_000 picoseconds.
		Weight::from_parts(32_471_000, 3833)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::Schemas` (r:1025 w:0)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:1024 w:1024)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	fn update_schema_quorum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `132568`
		//  Estimated: `11104815`
		// Minimum execution time: 14_308_404_000 picoseconds.
		Weight::from_parts(14_572_079_000, 11104815)
			.saturating_add(RocksDbWeight::get().reads(2050_u64))
			.saturating_add(RocksDbWeight::get().writes(1024_u64))
	}
	/// Storage: `Tables::BlockEnforcement` (r:0 w:1)
	/// Proof: `Tables::BlockEnforcement` (`max_values`: None, `max_size`: Some(149), added: 2624, mode: `MaxEncodedLen`)
	fn set_block_enforcement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_033_000 picoseconds.
		Weight::from_parts(7_454_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Tables::TableMetadata` (r:0 w:1)
	/// Proof: `Tables::TableMetadata` (`max_values`: None, `max_size`: Some(8424), added: 10899, mode: `MaxEncodedLen`)
	fn set_table_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 13_005_000 picoseconds.
		Weight::from_parts(13_395_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tables::NamespaceVersions` (r:1 w:0)
	/// Proof: `Tables::NamespaceVersions` (`max_values`: None, `max_size`: Some(166), added: 2641, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableVersions` (r:1 w:1)
	/// Proof: `Tables::TableVersions` (`max_values`: None, `max_size`: Some(232), added: 2707, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Identifiers` (r:1 w:1)
	/// Proof: `Tables::Identifiers` (`max_values`: None, `max_size`: Some(276824089), added: 276826564, mode: `MaxEncodedLen`)
	/// Storage: `Tables::Schemas` (r:1024 w:1)
	/// Proof: `Tables::Schemas` (`max_values`: None, `max_size`: Some(8358), added: 10833, mode: `MaxEncodedLen`)
	/// Storage: `Commitments::CommitmentStorageMap` (r:2 w:2)
	/// Proof: `Commitments::CommitmentStorageMap` (`max_values`: None, `max_size`: Some(45497), added: 47972, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableSources` (r:0 w:1)
	/// Proof: `Tables::TableSources` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableInsertQuorums` (r:0 w:1)
	/// Proof: `Tables::TableInsertQuorums` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Tables::ColumnVersions` (r:0 w:1)
	/// Proof: `Tables::ColumnVersions` (`max_values`: None, `max_size`: Some(8616), added: 11091, mode: `MaxEncodedLen`)
	/// Storage: `Tables::BlockEnforcement` (r:0 w:1)
	/// Proof: `Tables::BlockEnforcement` (`max_values`: None, `max_size`: Some(149), added: 2624, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableOwners` (r:0 w:1)
	/// Proof: `Tables::TableOwners` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	/// Storage: `Tables::TableMetadata` (r:0 w:1)
	/// Proof: `Tables::TableMetadata` (`max_values`: None, `max_size`: Some(8424), added: 10899, mode: `MaxEncodedLen`)
	fn create_table_with_sci_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `110046`
		//  Estimated: `276827554`
		// Minimum execution time: 6_627_318_000 picoseconds.
		Weight::from_parts(6_700_695_000, 276827554)
			.saturating_add(RocksDbWeight::get().reads(1030_u64))
			.saturating_add(RocksDbWeight::get().writes(11_u64))
	}
}
