CREATE TABLE IF NOT EXISTS SXT_SYSTEM_STAKING.NODEREGISTERED(
    BLOCK_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    TRANSACTION_HASH VARCHAR NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS VARCHAR NOT NULL,
    DECODE_ERROR VARCHAR NOT NULL,
    NODEPUBLICKEY VARCHAR NOT NULL,
    OPERATOR VARCHAR NOT NULL,
    PRIMARY KEY(BLOCK_NUMBER, EVENT_INDEX)
);

CREATE TABLE IF NOT EXISTS SXT_SYSTEM_STAKING.UNSTAKEINITIATED(
    BLOCK_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    TRANSACTION_HASH VARCHAR NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS VARCHAR NOT NULL,
    DECODE_ERROR VARCHAR NOT NULL,
    STAKER VARCHAR NOT NULL,
    PRIMARY KEY(BLOCK_NUMBER, EVENT_INDEX)
);

CREATE TABLE IF NOT EXISTS SXT_SYSTEM_STAKING.NOMINATE(
    BLOCK_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    TRANSACTION_HASH VARCHAR NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS VARCHAR NOT NULL,
    DECODE_ERROR VARCHAR NOT NULL,
    NODES VARCHAR NOT NULL,
    NOMINATOR VARCHAR NOT NULL,
    PRIMARY KEY(BLOCK_NUMBER, EVENT_INDEX)
);

CREATE TABLE IF NOT EXISTS SXT_SYSTEM_STAKING.UNSTAKECANCELLED(
    BLOCK_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    TRANSACTION_HASH VARCHAR NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS VARCHAR NOT NULL,
    DECODE_ERROR VARCHAR NOT NULL,
    STAKER VARCHAR NOT NULL,
    PRIMARY KEY(BLOCK_NUMBER, EVENT_INDEX)
);

CREATE TABLE IF NOT EXISTS SXT_SYSTEM_STAKING.STAKED(
    BLOCK_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    TRANSACTION_HASH VARCHAR NOT NULL,
    EVENT_INDEX INT NOT NULL,
    CONTRACT_ADDRESS VARCHAR NOT NULL,
    DECODE_ERROR VARCHAR NOT NULL,
    NODES VARCHAR NOT NULL,
    STAKER VARCHAR NOT NULL,
    AMOUNT DECIMAL(75, 0) NOT NULL,
    PRIMARY KEY(BLOCK_NUMBER, EVENT_INDEX)
);
