CREATE TABLE IF NOT EXISTS ETHEREUM_BEACON.BLOCKS (
    BLOCK_NUMBER BIGINT NOT NULL,
    SLOT_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    EPOCH_NUMBER BIGINT NOT NULL,
    PROPOSER_INDEX BIGINT NOT NULL,
    PARENT_ROOT BINARY NOT NULL,
    STATE_ROOT BINARY NOT NULL,
    RANDAO_REVEAL BINARY NOT NULL,
    GRAFFITI BINARY NOT NULL,
    ETH1_BLOCK_HASH BINARY NOT NULL,
    ETH1_DEPOSIT_COUNT BIGINT NOT NULL,
    ETH1_DEPOSIT_ROOT BINARY NOT NULL,
    SIGNATURE BINARY NOT NULL,
    BLOB_GAS_USED BIGINT NOT NULL,
    EXCESS_BLOB_GAS BIGINT NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, SLOT_NUMBER)
);

CREATE TABLE IF NOT EXISTS ETHEREUM_BEACON.DEPOSITS (
    BLOCK_NUMBER BIGINT NOT NULL,
    SLOT_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    DEPOSIT_AMOUNT BIGINT NOT NULL,
    PUBKEY BINARY NOT NULL,
    SIGNATURE BINARY NOT NULL,
    WITHDRAWAL_CREDENTIALS BINARY NOT NULL,
    EPOCH_NUMBER BIGINT NOT NULL,
    DEPOSIT_INDEX INT NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, SLOT_NUMBER, DEPOSIT_INDEX)
);

CREATE TABLE IF NOT EXISTS ETHEREUM_BEACON.WITHDRAWALS (
    BLOCK_NUMBER BIGINT NOT NULL,
    SLOT_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    WITHDRAWAL_INDEX BIGINT NOT NULL,
    VALIDATOR_INDEX BIGINT NOT NULL,
    ADDRESS ADDRESS NOT NULL,
    AMOUNT BIGINT NOT NULL,
    EPOCH_NUMBER BIGINT NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, SLOT_NUMBER, WITHDRAWAL_INDEX)
);

CREATE TABLE IF NOT EXISTS ETHEREUM_BEACON.ATTESTATIONS (
    BLOCK_NUMBER BIGINT NOT NULL,
    SLOT_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    EPOCH_NUMBER BIGINT NOT NULL,
    ATTESTATION_INDEX BIGINT NOT NULL,
    AGGREGATION_BITS VARCHAR NOT NULL,
    BEACON_BLOCK_ROOT BINARY NOT NULL,
    SOURCE_EPOCH BIGINT NOT NULL,
    SOURCE_ROOT BINARY NOT NULL,
    TARGET_EPOCH BIGINT NOT NULL,
    TARGET_ROOT BINARY NOT NULL,
    ATTESTATION_SIGNATURE BINARY NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, SLOT_NUMBER, ATTESTATION_INDEX)
);

CREATE TABLE IF NOT EXISTS ETHEREUM_BEACON.BLOB_SIDECARS (
    BLOCK_NUMBER BIGINT NOT NULL,
    SLOT_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    EPOCH_NUMBER BIGINT NOT NULL,
    BLOB VARCHAR NOT NULL,
    BLOB_INDEX BIGINT NOT NULL,
    KZG_COMMITMENT BINARY NOT NULL,
    KZG_PROOF BINARY NOT NULL,
    BODY_ROOT BINARY NOT NULL,
    PARENT_ROOT BINARY NOT NULL,
    PROPOSER_INDEX BIGINT NOT NULL,
    STATE_ROOT BINARY NOT NULL,
    ATTESTATION_SIGNATURE BINARY NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, SLOT_NUMBER, BLOB_INDEX)
);

CREATE TABLE IF NOT EXISTS ETHEREUM_BEACON.BLOB_SIDECAR_KZG_COMMITMENT_INCLUSION_PROOFS (
    BLOCK_NUMBER BIGINT NOT NULL,
    SLOT_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    EPOCH_NUMBER BIGINT NOT NULL,
    BLOB_INDEX BIGINT NOT NULL,
    KZG_COMMITMENT_INCLUSION_PROOF_INDEX INT NOT NULL,
    KZG_COMMITMENT_INCLUSION_PROOF_VALUE BINARY NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, SLOT_NUMBER, BLOB_INDEX, KZG_COMMITMENT_INCLUSION_PROOF_INDEX)
);

CREATE TABLE IF NOT EXISTS ETHEREUM_BEACON.VALIDATOR_BALANCES (
    BLOCK_NUMBER BIGINT NOT NULL,
    SLOT_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    EPOCH_NUMBER BIGINT NOT NULL,
    STATE_ID BINARY NOT NULL,
    VALIDATOR_INDEX BIGINT NOT NULL,
    BALANCE BIGINT NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, SLOT_NUMBER, VALIDATOR_INDEX)
);

CREATE TABLE IF NOT EXISTS ETHEREUM_BEACON.ATTESTER_SLASHINGS (
    BLOCK_NUMBER BIGINT NOT NULL,
    SLOT_NUMBER BIGINT NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    EPOCH_NUMBER BIGINT NOT NULL,
    ATTESTATION_1_BEACON_BLOCK_ROOT BINARY NOT NULL,
    ATTESTATION_1_INDEX BIGINT NOT NULL,
    ATTESTATION_1_SLOT BIGINT NOT NULL,
    ATTESTATION_1_SOURCE_EPOCH BIGINT NOT NULL,
    ATTESTATION_1_SOURCE_ROOT BINARY NOT NULL,
    ATTESTATION_1_TARGET_EPOCH BIGINT NOT NULL,
    ATTESTATION_1_TARGET_ROOT BINARY NOT NULL,
    ATTESTATION_1_SIGNATURE BINARY NOT NULL,
    PRIMARY KEY (BLOCK_NUMBER, SLOT_NUMBER)
);
