name: gchr

on:
  push:
    branches:
      - main
    paths:
      - publish/docker/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build_node:
    uses: ./.github/workflows/publish_shared.yml
    with:
      IMAGE_NAME: sxt-node
      working-directory: publish/docker
    secrets: inherit
