name: gchr

on:
  push:
    branches:
      - main
    paths:
      - publish/docker/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build_node:
    uses: ./.github/workflows/publish_shared.yml
    with:
      SRC_IMAGE_NAME: sxtnode-docker-local/sxt-node
      PUB_IMAGE_NAME: sxt-node
      working-directory: publish/docker/sxt-node
    secrets: inherit
  build_attestor:
    uses: ./.github/workflows/publish_shared.yml
    with:
      SRC_IMAGE_NAME: sxt-node/watcher
      PUB_IMAGE_NAME: sxt-attestor
      working-directory: publish/docker/sxt-attestor
    secrets: inherit