name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Run Release Manager

    runs-on: large-4-core-16gb-22-04

    steps:
      - name: Load Secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          GITHUB_APP_ID: op://op-github-devops/cosmic-agent-labs/app-id
          GITHUB_PRIVATE_KEY: op://op-github-devops/cosmic-agent-labs/private-key
          ARTIFACTORY_USER: op://op-github-devops/jfrog_devops/username
          ARTIFACTORY_API_KEY: op://op-github-devops/jfrog_devops/token

      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ env.GITHUB_APP_ID }}
          private-key: ${{ env.GITHUB_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          # Pull all previous tags
          fetch-depth: 0
          fetch-tags: true

      - name: Conventional Changelog Action
        id: conventional-changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          skip-git-pull: true
          skip-version-file: true
          git-push: false
          skip-on-empty: false # Always create commit

      - name: Push Conventional Changelog
        uses: ad-m/github-push-action@master
        id: push
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          branch: ${{ github.ref }}

      - uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: https://spaceandtime.jfrog.io/
          JF_USER: ${{ env.ARTIFACTORY_USER }}
          JF_PASSWORD: ${{ env.ARTIFACTORY_API_KEY }}

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # 1.3.1
        with:
          android: true # This alone is a 12 GB save.
          # We disable the rest because it caused some problems. (they're enabled by default)
          # The Android removal is enough.
          dotnet: false
          haskell: false
          large-packages: false
          swap-storage: false

      - name: Rust compilation prerequisites
        run: |
          sudo apt update
          sudo apt install -y \
            protobuf-compiler
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src

      - name: Build and Release SxT-Node Binaries
        run: |-
          cargo build --locked --release
          jf rt u --flat target/release/sxt-node sxtnode-generic-local/sxt-node/${{ steps.conventional-changelog.outputs.version }}/;
          jf rt u --flat target/release/wbuild/sxt-runtime/sxt_runtime.compact.compressed.wasm sxtnode-generic-local/sxt-node/${{ steps.conventional-changelog.outputs.version }}/;
        timeout-minutes: 90

      - name: Build and Release Dockerfile
        env:
          DOCKERTAG: spaceandtime.jfrog.io/sxtnode-docker-local/sxt-node:${{ steps.conventional-changelog.outputs.version }}
        run: |-
          docker buildx version
          docker buildx ls
          export ARTIFACTORY_LOGIN=$ARTIFACTORY_USER:$ARTIFACTORY_API_KEY
          docker buildx build -f ./sxtnode.Dockerfile --secret id=ARTIFACTORY_LOGIN . -t $DOCKERTAG
          jf docker push $DOCKERTAG
        timeout-minutes: 90

      # Need to regenerate Github App token as previous steps take more than 60 minutes to complete
      # and hence previous token expires.
      - name: Re-create GitHub App Token
        id: app-token-release
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ env.GITHUB_APP_ID }}
          private-key: ${{ env.GITHUB_PRIVATE_KEY }}


      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.conventional-changelog.outputs.tag }}
          body: ${{ steps.conventional-changelog.outputs.changelog }}
          token: ${{ steps.app-token-release.outputs.token }} # Using Github Auth token created in step above
          makeLatest: true
