//! TODO: add docs
#![cfg_attr(not(feature = "std"), no_std)]
#![cfg_attr(
    all(feature = "std", feature = "proptest"),
    warn(unused_crate_dependencies)
)]

extern crate alloc;
extern crate core;

use polkadot_sdk::sp_core::ConstU32;
use polkadot_sdk::sp_runtime::BoundedVec;

/// Types and functionality related to the permissions system
pub mod permissions;

/// Types and Functionality related to parsing system messages
pub mod parse;

/// Types and functionality related to tables
pub mod tables;

/// Types primarily used by the indexing pallet for data submissions and quorum finding
pub mod indexing;

/// Types consumed by the native code interface
pub mod native;

pub mod attestation;

/// Shared items for the prover-db-indexer pallet, its producer call
/// sites in `pallet-tables` / `pallet-indexing`, and the node service
/// that seeds its configuration.
pub mod prover_db_indexer;

/// Autogenerated code used by Subxt to interact with the network as a client
#[cfg(all(feature = "std", not(doctest)))]
#[allow(missing_docs)]
pub mod sxt_chain_runtime;
/// The maximum length of Identifiers
pub const IDENT_LENGTH: u32 = 64;

/// The maximum length of u8 strings in the system
pub type IdentLength = ConstU32<IDENT_LENGTH>;

/// A IdentLength length bounded vector of u8 data, represents the basic string type on the substrate side.
pub type ByteString = BoundedVec<u8, IdentLength>;

/// Types related to the keystore pallet
pub mod keystore;

/// Types needed for pallet-smartcontracts
pub mod smartcontracts;

/// Types related to the system contracts pallet;
pub mod system_contracts;

/// Types related to the system tables pallet
pub mod system_tables;

/// Utility functions for handling Runtime types
pub mod utils;

pub mod heavy;

/// Utility functions related to record batches.
pub mod record_batch;

#[cfg(feature = "proptest")]
pub mod proptest;
